name: Build Push and Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::558931385457:role/zzw-github-access
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image to ECR
        run: |
          IMAGE_URI=558931385457.dkr.ecr.ap-northeast-1.amazonaws.com/my_app:latest
          docker build --no-cache -t $IMAGE_URI ./my_app_python
          docker push $IMAGE_URI

      - name: Check ECS cluster exists
        id: check-ecs
        run: |
          if aws ecs describe-clusters \
            --clusters my-app-cluster \
            --region ap-northeast-1 \
            --query "clusters[0].status" \
            --output text | grep -q ACTIVE; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Force new ECS deployment
        if: steps.check-ecs.outputs.exists == 'true'
        run: |
          aws ecs update-service \
            --cluster my-app-cluster \
            --service my-app-service \
            --force-new-deployment \
            --region ap-northeast-1

      - name: Skip ECS deployment
        if: steps.check-ecs.outputs.exists == 'false'
        run: |
          echo "ECS cluster does not exist. Skip deployment."